version: '3.3'

services:
  php:
    build: .
    ports:
      - "80:80"
    environment:
      MYSQL_PASS: bH2FGYKdZIA8
    volumes:
      - .:/var/www/html
  composer:
    image: composer
    command: [ "composer", "update" ]
    volumes:
      - .:/app